# Generated by Django 4.2.19 on 2025-02-28 10:05

from django.db import migrations, models
import document_processing.validators.email_validator


class Migration(migrations.Migration):

    dependencies = [
        ('document_processing', '0002_document_extracted_text_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='rag_status',
            field=models.CharField(default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='email',
            field=models.EmailField(max_length=254, validators=[document_processing.validators.email_validator.validate_email_address]),
        ),
    ]
