import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="inline-flex h-full w-full items-center justify-center">
          <Link
            href={`/upload`}
            className="inline-block
                      rounded-md px-4 py-2 bg-white hover:bg-indigo-400 text-sm text-indigo-500 hover:text-white focus:relative"
          >
            Upload CV
          </Link>

          <Link
            href={`/chat`}
            className="ml-4 rounded-md px-4 py-2 bg-white hover:bg-indigo-400 text-sm
                        text-indigo-500 hover:text-white focus:relative"
          >
            Chat UI
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
